<!------------------------------------------------------------------------
-- Plantilla HTML para la página de portada del panel de administración --
------------------------------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/../layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/../header.phtml';?>

<h1>Añadir noticia</h1>

<form action="" method="post" enctype="multipart/form-data">
    <input type="text" name="title" placeholder="Título" value="<?php if (isset($title)) echo $title?>">
    <input type="text" name="subtitle" placeholder="subtítulo" value="<?php if (isset($subtitle)) echo $subtitle?>">
    <select name="category_id">
        <?php
        if (isset($categories)) {
            foreach ($categories as $id => $name) {
                $selected = (isset($category_id) && $category_id == $id) ? 'selected' : '';
                echo "<option value='{$id}' {$selected}>{$name}</option>";
            }
        }
        ?>
    </select>
<?php
if (isset($img) && $img) {
    echo "<img src='/yaseal-local/public/img/news/$img' height='200' width='200'/>";
}
?>
    <input type='file' name='img'>
    <textarea name="content"><?php if (isset($content)) echo $content?></textarea>
    <input type="text" name="keywords" placeholder="Ej: keyword, list, example" value="<?php if (isset($keywords)) echo $keywords?>">
    <?php if (isset($action) && $action == "edit") {
        echo "<button type='submit'>Editar</button>";
    } else {
        echo "<button type='submit'>Añadir</button>";
    }
    ?>
</form>
<?php
if (isset($notification)) {
    echo "<div>{$notification['msg']}</div>";
}
?>

<?php /* incluimos el footer */ include __DIR__ . '/../footer.phtml' ?>