<!-------------------------------------------------
-- Plantilla HTML para el footer del admin panel --
--------------------------------------------------->
<footer class="admin-footer row">
    <p>Equipo Yaseal - Proyecto UOC - Actividad 4</p>
</footer>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript" src="/public/js/admin-main.js"></script>
</body>
</html>