<!---------------------------------------------------
-- Plantilla HTML para la cabecera del admin panel --
---------------------------------------------------->
<header class="admin-header">
    <div class="area-logo">
        <i class="fas fa-chart-area"></i>
    </div>
    <div class="area-title">
        <a href="/"><h3>YASEAL</h3></a>
    </div>
    <div class="area-profile">
        <div class="user column">
            <i class="far fa-user-circle"></i>
            <span><?php echo $_SESSION['user']->getName() ?></span>
        </div>
        <div class="logout">
            <a href="/logout">
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </div>
    </div>
</header>