<!------------------------------------------------------------------------
-- Plantilla HTML para el sidebar IZ del admin panel --
------------------------------------------------------------------------->
<aside class="sidebar-left column start">
    <a href="./panel">
        <i class="far fa-newspaper"></i>
        Articulos 
    </a>
    <a href="./profile">
        <i class="far fa-user-circle"></i>
        Perfil
    </a>
</aside>