<!------------------------------------------------------------------------
-- Plantilla HTML para la página de portada del panel de administración --
------------------------------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="panel">
<aside class="sidebar-left"></aside>
<section class="content">
    <div class="header">
        <div class="title">
            <h1>Articulos</h1>
            <div class="area-button">
                <?php
                if ($_SESSION['user']->getRole() != 'editor') {
                echo "<a class='button outline red' href='add'>Añadir Noticia</a>";
                }
                ?>
                <a class="button outline red">Botones</a>
            </div>
        </div>
        <div class="filters">
            <span>Ordenar por</span>
            <span>Buscar</span>
        </div>
    </div>
    <div class="list">
        <div class='card titles'>
            <div class='card-content'>Título</div>
            <div class='card-content'>Categoría</div>
            <div class='card-content'>Fecha de creación</div>
            <div class='card-content'>Fecha de publicación</div>
            <div class='card-content'>Autor</div>
            <div class='clear'></div>
        </div>
<?php
if (isset($news) && $news) {
    foreach ($news as $item) {
        echo "<div class='card'>
                <div class='card-content'><a href='/admin_panel/edit/{$item->getId()}'>{$item->getTitle()}</a></div>
                <div class='card-content'>{$categories[$item->getCategory()]}</div>
                <div class='card-content'>{$item->getDateCreated()}</div>
                <div class='card-content'>{$item->getDatePublished()}</div>
                <div class='card-content'>{$item->getAutor()->getName()}</div>
                <div class='clear'></div>
              </div>";
    }
} else {
    echo "<div class='card'><div class='card-content'>No hay nada que mostrar</div></div>";
}
?>
    </div>
<br>

<?php
    if (isset($notification)) {
        $cssClas = $notification['type'];
        echo "<div class='$cssClas'>{$notification['msg']}</div>";
    }
    ?>

<br>
    </section>
    <aside class="sidebar-rigth"></aside>
</main>

<?php /* incluimos el footer */ include __DIR__ . '/../footer.phtml' ?>