<!------------------------------------------------------------------------
-- Plantilla HTML para la página de Perfil del admin panel --
------------------------------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="panel">
<?php /* incluimos la cabecera */ include __DIR__ . '/left_aside.phtml' ?>
<section class="content">
    <div class="header">
        <div class="title">
            <h1>Perfil</h1>
            <div class="area-button">
                <a class='button outline blue round' href='#'>Guardar</a>
            </div>
        </div>
        <div class="filters"></div>
    </div>

    <div class="information column">
        <div class='card'>
            <form id="profile-form" action="#" method="post" class="gray">
                <input type="text" name="name" placeholder="Nombre y Apellidos" <?php if (isset($name)) echo "value=$name"?>>
                <input type="text" name="email" placeholder="Email" <?php if (isset($email)) echo "value=$email"?>>
                <input type="password" name="password" placeholder="Contraseña">
            </form>
        </div>
    </div>

    <?php if (isset($notification)) {
        $cssClas = $notification['type']; ?>
        <div class='<?php $cssClas ?>'>
            <?php echo $notification['msg'] ?>
        </div>
    <?php } ?>

</section>
<?php /* incluimos el sidebar */ include __DIR__ . '/right_aside.phtml' ?>
</main>
<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>