<!------------------------------------------------------------------------
-- Plantilla HTML para la página de Perfil del admin panel --
------------------------------------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<main class="panel">
<?php /* incluimos la cabecera */ include __DIR__ . '/left_aside.phtml' ?>
<section class="content">
    <div class="header">
        <div class="title">
            <h1>Perfil</h1>
            <div class="area-button">
                <input type="submit" class='button outline blue round' form="profile-form" value ="Guardar">
            </div>
        </div>
        <div class="filters"></div>
    </div>

    <div class="information column">
        <div class='card'>
            <form id="profile-form" class="gray" action="#">
                <input type="text" name="name" placeholder="Nombre y Apellidos" value="<?php echo $user->getName() ?>" >
                <input type="text" name="email" placeholder="Email" value="<?php echo $user->getEmail() ?>" >
                <input type="password" name="password" placeholder="Contraseña" value="" >
            </form>
        </div>
    </div>

    <div id="errors-form"></div>

</section>
<?php /* incluimos el sidebar */ include __DIR__ . '/right_aside.phtml' ?>
</main>
<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>