<!-----------------------------------
-- Plantilla HTML para la cabecera --
------------------------------------>
<header>
<?php 
    $cssPath = './public/css/home.css';
    echo "<link rel='stylesheet' href={$cssPath}>
    <link rel='stylesheet' href='./public/css/reset.css'>";
?>


<nav class="navigation-bar"> 
    <p class="logo">Yaseal</p>
    <a href="./internacional">INTERNACIONAL</a>
    <a href="./local">LOCAL</a>
    <a href="./deportes">DEPORTES</a>
    <a href="./tiempo">TIEMPO</a>
</nav>
</header>