<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>
<link rel="stylesheet" href="/public/css/home.css">

<div class=noticias>

  <?php 

    $newsArray = $_SESSION['news'];
    $mainNew = $newsArray[''];
    $mainNew = $mainNew[0];

    $mainNewUrl = "/noticia/" . (string)$mainNew->getId();

    echo "<div class='portada'>
            <img class='img-portada' src='/public/img/news/{$mainNew->getImg()}' alt='portada'>
            <div class='texto-portada' style='text-shadow: 1px 1px 1px black;;'>
              <h1 id='titulo-portada'>{$mainNew->getTitle()}</h1>
              <span id='fecha-portada'>{$mainNew->getDateCreated()}</span>
            </div>
          </div>";

    foreach($newsArray as $newsCategory => $news) {
      if($newsCategory !== '') {
        echo "<section class='cards'>
                <h2 class='titulo-seccion'>{$newsCategory}</h2>  
              </section>";
      }
      echo  " <section class='cards'>";
      foreach($news as $new) {
        $newUrl = "./noticia/" . (string)$new->getId();
          echo "<article href={$newUrl}>
                  <a href={$newUrl}> <img class='article-img' src='/public/img/news/{$new->getImg()}' alt=''/></a>
                  <a href={$newUrl}> <h3 class='article-title'>{$new->getTitle()}</h3></a>
                </article> "; 
      }
      echo " </section>";
    }
  
  ?>

</div>

<script type="text/javascript" src="./public/js/admin-main.js"></script>
<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>