<!------------------------------------
-- Plantilla HTML global para todas --
------------------------------------->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Noticias</title>

    <link rel="stylesheet" href="/public/css/reset.css">
    <link rel='stylesheet' href='/public/css/noticia.css'>
</head>
<body>
    