<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>
<link rel="stylesheet" href="./public/css/home.css">

<div class="portada">
    <img class="img-portada" src="public\images\portada.jpg" alt="portada">
    <div class="texto-portada">
    <h1 id="titulo-portada">Conoce las últimas noticias locales</h1>
    
    </div>
</div>


<div class=noticias>
<section class="cards">

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/305/205" alt=" "/></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/320/220" alt=" " /></a>
        <a href=""><h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/330/240" alt=" " /></a>
        <a href=""><h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>
      </section>

    
      <section class="cards">
        <h2 class="titulo-seccion">España</h2>  
      </section>
      <section class="cards">
    
        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/305/205" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/320/220" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/330/240" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>
      </section>

      <section class="cards">
        <h2 class="titulo-seccion">Cataluña</h2>  
      </section>
      <section class="cards">
    
        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/305/205" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/320/220" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/330/240" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>
      </section>

      <section class="cards">
        <h2 class="titulo-seccion">Barceloa</h2>  
      </section>
      <section class="cards">
    
        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/305/205" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/320/220" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>

        <article>
        <a href=""><img class="article-img" src="http://placekitten.com/330/240" alt=" " /></a>
        <a href=""> <h3 class="article-title">Título de la noticia</h3></a>
          <p>Aquí va el texto de la noticia a medio de introducción para el lector </p>
        </article>
      </section>


</div>

<script type="text/javascript" src="./public/js/admin-main.js"></script>
<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>
</section>