<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>
<link rel="stylesheet" href="./public/css/noticia.css">

<div class="portada">
<div style="text-align:center;" class="cabecera-noticia">

    <hr>
    <h1 class="titular-noticia">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla a libero sit amet nulla.<h1>
    <hr>   
    <img class="img-portada" src="public\images\portada.jpg" alt="portada">
    <hr>
    <div style="text-align:center;" class="pie-pagina">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla a libero sit amet nulla viverra egestas ut a nisi.</p>
    </div>
    <hr>
</div>
</div>
<div class="texto-noticia">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla a libero sit amet nulla viverra egestas ut a nisi. Mauris mattis sollicitudin nulla vel convallis.
    Donec eu nunc dapibus elit volutpat bibendum. Nulla diam dui, aliquam non mollis vitae, feugiat sed enim. Aliquam nibh tellus, finibus sed finibus commodo, egestas
    eget diam. Aenean rhoncus ullamcorper nibh, quis viverra ligula accumsan eget. Maecenas nec ex eu leo faucibus iaculis ut ultrices elit. Morbi tincidunt est ante,
    vitae suscipit turpis condimentum ac. Aliquam cursus interdum ullamcorper. Phasellus mattis nunc mauris, ac faucibus orci congue sit amet. Proin vel elit augue.
    Pellentesque rutrum lacus a porta lobortis. Sed ac sapien ligula. Suspendisse potenti. In ac congue sem. Quisque finibus, augue id euismod ultrices, lectus lacus
    maximus sem, eu placerat nulla magna iaculis arcu.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in posuere metus. Donec vitae molestie urna. Nulla maximus, quam at molestie congue, magna tortor luctus 
    mauris, at volutpat nunc tortor vitae risus. Nullam dui arcu, feugiat ac lectus non, luctus dignissim sapien. Duis pellentesque magna in nibh finibus vulputate. 
    Vestibulum vitae justo quis urna auctor sagittis. Phasellus consequat odio nec lorem iaculis, id ultricies turpis varius. Phasellus in ligula bibendum, 
    tincidunt turpis consequat, egestas quam. Pellentesque non nisl ac massa varius tristique. Pellentesque habitant morbi tristique senectus et netus 
    et malesuada fames ac turpis egestas. Nunc lobortis hendrerit est, ut posuere eros dapibus vel. Donec dignissim tellus at molestie sollicitudin. 
    Proin lorem magna, maximus a mi viverra, efficitur pharetra sem.</p> 

      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla a libero sit amet nulla viverra egestas ut a nisi. Mauris mattis sollicitudin nulla vel convallis.
    Donec eu nunc dapibus elit volutpat bibendum. Nulla diam dui, aliquam non mollis vitae, feugiat sed enim. Aliquam nibh tellus, finibus sed finibus commodo, egestas
    eget diam. Aenean rhoncus ullamcorper nibh, quis viverra ligula accumsan eget. Maecenas nec ex eu leo faucibus iaculis ut ultrices elit. Morbi tincidunt est ante,
    vitae suscipit turpis condimentum ac. Aliquam cursus interdum ullamcorper. Phasellus mattis nunc mauris, ac faucibus orci congue sit amet. Proin vel elit augue.
    Pellentesque rutrum lacus a porta lobortis. Sed ac sapien ligula. Suspendisse potenti. In ac congue sem. Quisque finibus, augue id euismod ultrices, lectus lacus
    maximus sem, eu placerat nulla magna iaculis arcu.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in posuere metus. Donec vitae molestie urna. Nulla maximus, quam at molestie congue, magna tortor luctus 
    mauris, at volutpat nunc tortor vitae risus. Nullam dui arcu, feugiat ac lectus non, luctus dignissim sapien. Duis pellentesque magna in nibh finibus vulputate. 
    Vestibulum vitae justo quis urna auctor sagittis. Phasellus consequat odio nec lorem iaculis, id ultricies turpis varius. Phasellus in ligula bibendum, 
    tincidunt turpis consequat, egestas quam. Pellentesque non nisl ac massa varius tristique. Pellentesque habitant morbi tristique senectus et netus 
    et malesuada fames ac turpis egestas. Nunc lobortis hendrerit est, ut posuere eros dapibus vel. Donec dignissim tellus at molestie sollicitudin. 
    Proin lorem magna, maximus a mi viverra, efficitur pharetra sem.</p> 

    <div class="firma">
    <span class="autor">Autor del articulo </span>
    <span> | </span>
    <span class="fecha">Fecha del articulo </span>
    </div>
</div>

