<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>
<link rel="stylesheet" href="/public/css/home.css">
<?php 
  $newsArray = $_SESSION['news'];
  foreach($newsArray as $newsCategory => $news) {
  echo "<div class='portada'>
      <img class='img-portada' src='public\images\portada.jpg' alt='portada'>
      <div class='texto-portada'>
      <h1 id='titulo-portada'>Conoce las últimas noticias {$newsCategory}</h1>
      
      </div>
  </div>

  <div class=noticias>
    <section class='cards'>";
    foreach($news as $new) {
      $newUrl = "./noticia/" . (string)$new->getId();
        echo "<article href={$newUrl}>
                <a href={$newUrl}> <img class='article-img' src={$new->getImg()} alt=''/></a>
                <a href= href={$newUrl}> <h3 class='article-title'>{$new->getTitle()}</h3></a>
                  <p>{$new->getContent()} </p>
              </article> "; 
    }
    echo " </section>";
  }

?>

</div>

<script type="text/javascript" src="./public/js/admin-main.js"></script>
<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>
</section>